version: "3.8"
services:
  web:
    build: ./app
    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
    image: 305790585397.dkr.ecr.us-east-2.amazonaws.com/django_docker_aws:django_docker_aws_web

    volumes:
      - ./app/:/usr/src/app/
      - static_volume:/usr/src/app/static
    expose:
      - 8000
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/static
    image: 305790585397.dkr.ecr.us-east-2.amazonaws.com/django_docker_aws:django_docker_aws_nginx

    ports:
      - 8000:80
    depends_on:
      - web
volumes:
  static_volume:


